name: Release VScode Extension

env:
  NODE_VERSION: 20.x

on:
  push:
    tags:
      - 'v*.*.*'
  workflow_dispatch:

jobs:
  # ================================
  # Job 2: æ‰“åŒ…å¹¶å‘å¸ƒåˆ° VS Code å¸‚åœº
  # ================================
  publish-extension:
    name: ğŸ“¦ æ„å»ºå‘å¸ƒ VScode æ’ä»¶
    runs-on: ubuntu-latest

    steps:
      - name: ğŸ” 1. æ‹‰å–ä»£ç ï¼ˆåŒ…å«æ–°ç‰ˆæœ¬å·çš„ package.jsonï¼‰
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # å¿…é¡»å®Œæ•´å†å²ä»¥æ”¯æŒ semantic-release åˆ¤æ–­å˜æ›´

      - name: âš™ï¸ 2. è®¾ç½® Node.js ç¯å¢ƒ
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'

      - name: ğŸ“‹ 3. è·å–ç‰ˆæœ¬å·
        id: get_info
        run: |
          name=$(node -p "require('./package.json').name")
          version=$(node -p "require('./package.json').version")
          echo "name=$name" >> $GITHUB_OUTPUT
          echo "version=$version" >> $GITHUB_OUTPUT
          echo "ğŸ‘‰ğŸ‘‰ğŸ‘‰ æ’ä»¶å: $name"
          echo "ğŸ‘‰ğŸ‘‰ğŸ‘‰ ç‰ˆæœ¬å·: $version"
          echo "ğŸ‘‰ğŸ‘‰ğŸ‘‰ ${{ github.ref_name }}"

      - name: ğŸ“¦ 4. å®‰è£…ä¾èµ–
        run: npm ci

      - name: === æ‰“åŒ…æ‰©å±•
        id: package_extension
        uses: HaaLeo/publish-vscode-extension@v1
        with:
          pat: stub
          dryRun: true

      - name: ğŸš€ 5. ä¸Šä¼ åˆ° GitHub Releases
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.MY_PERSONAL_TOKEN }}
          file_glob: true
          file: ${{ steps.package_extension.outputs.vsixPath }}
          overwrite: true
          tag: ${{ github.ref_name }}

      - name: ğŸš€ 6. ä¸Šä¼ åˆ° VSCode Marketplace
        uses: HaaLeo/publish-vscode-extension@v1
        with:
          pat: ${{ secrets.VSCODE_MARKETPLACE_TOKEN }}
          registryUrl: https://marketplace.visualstudio.com
          extensionFile: ${{ steps.package_extension.outputs.vsixPath }}

      - name: ğŸš€ 7. ä¸Šä¼ åˆ° GitHub Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ steps.get_info.outputs.name }}-${{ steps.get_info.outputs.version }}
          path: ${{ steps.package_extension.outputs.vsixPath }}
